export const END_POINT = {
  SIGN_UP: "signup",
  VERIFY_EMAIL: "confirm-email",
  CONFIRM_REGISTER: "confirm-register",
  LOGIN: "login",
  PROFILE: "user",
  LOGOUT: "logout",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  CHANGE_PASSWORD: "change-password",
  PRODUCTS: "products",
  USERS: "users",
  CATEGORIES: "categories",
  LATESTTUSERS: "lastusers",
  BLOGS: "blogs",
  ORDERS: "orders",
  LATESTORDERS: "lastorders",
};
